language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs-1'
  - 'iojs-2'
  - 'iojs'
  - '6.0.0'
  - '6.1.0'
  - '6.2.0'
sudo: true
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libfann-dev
env:
  - CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
matrix:
  exclude:
    - node_js: 0.10
      env: CXX=g++-5
    - node_js: 0.12
      env: CXX=g++-5
    - node_js: iojs-1
      env: CXX=g++-5
    - node_js: iojs-2
      env: CXX=g++-5
script: npm install . && npm test
