language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs-1'
  - 'iojs-2'
sudo: true
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libfann-dev

matrix:
  include:
    - node_js: 'iojs'
      env: CXX=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
    - node_js: '6.0.0'
      env: CXX=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
    - node_js: '6.1.0'
      env: CXX=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
    - node_js: '6.2.0'
      env: CXX=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
script: npm install . && npm test
